/**
 * Encapsulate a unified API request object to simplify the use of fetch
 *
 * @remarks
 * docs generated by \@microsoft\/api-extractor & api-documenter, may not so good.
 *
 * @packageDocumentation
 */

export { default, urnParser } from './API'
export * from './type&interface'
