/**
 * Encapsulate a unified API request object to simplify the use of fetch
 *
 * @remarks
 * docs generated by \@microsoft\/api-extractor & api-documenter, may not so good.
 *
 * @packageDocumentation
 */

export { default as API, urnParser } from './API'
// export { default as globalThis } from './polyfill'
// export { globalThis } from './polyfill'
export * from './type&interface'
